version: 0.2

phases:
  install:
    commands:
      - echo We should be running unit tests here
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --region $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build Phase
      - docker build -t procell-website-$MODE:latest .
      - docker tag procell-website-$MODE:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/procell-website-$MODE:latest
  post_build:
    commands:
      - echo PostBuild Phase
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/procell-website-$MODE:latest
      - ./create-new-task-def.sh procell-website-$MODE

artifacts:
  files:
    - 'appspec.yml'
    - 'taskdef.json'
