#!/bin/bash
echo "NODE_ENV=${NODE_ENV}
NEXT_APP_JWT=${NEXT_APP_JWT}
NEXT_APP_TOKEN_NAME=${NEXT_APP_TOKEN_NAME}
NEXT_APP_BASE_URL=${NEXT_APP_BASE_URL}
NEXT_AUTHORIZATION_LOGIN_ID=${NEXT_AUTHORIZATION_LOGIN_ID}
NEXT_AUTHORIZATION_CLIENT_KEY=${NEXT_AUTHORIZATION_CLIENT_KEY}
NEXT_AUTHORIZATION_INSTAGRAM_ACCESS_TOKEN=${NEXT_AUTHORIZATION_INSTAGRAM_ACCESS_TOKEN}
NEXT_AUTHORIZATION_CRYPTO_SECRET_KEY=${NEXT_AUTHORIZATION_CRYPTO_SECRET_KEY}" > .env