export const GET_ACADEMY_INFO = "GET_ACADEMY_INFO";
export const GET_PRACTITIONER_ACADEMY_CONTENT = "GET_PRACTITIONER_ACADEMY_CONTENT";
export const GET_REP_ACADEMY_CONTENT = "GET_REP_ACADEMY_CONTENT";
export const GET_REP_ACADEMY_CONTENT_ID = "GET_REP_ACADEMY_CONTENT_ID";
export const GET_PRACTITIONER_ACADEMY_CONTENT_ID = "GET_PRACTITIONER_ACADEMY_CONTENT_ID";