export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";
export const GET_QUOTATION_LIST = "GET_QUOTATION_LIST";
export const GET_SALES_LIST = "GET_SALES_LIST";
export const GET_PURCHASE_LIST = "GET_PURCHASE_LIST";
export const GET_INVOICE_LIST = "GET_INVOICE_LIST";
export const GET_INVOICE_DOWNLOAD = "GET_INVOICE_DOWNLOAD";
export const GET_MANAGE_COMMUNICATION_DATA = "GET_MANAGE_COMMUNICATION_DATA";