export const GET_CLIENTS_LIST = "GET_CLIENTS_LIST";
export const GET_CLIENTS_ENTRIES = "GET_CLIENTS_ENTRIES";
export const GET_CLIENTS_DETAILS = "GET_CLIENTS_DETAILS";
export const GET_CLIENTS_ENTRY_DETAILS = "GET_CLIENTS_ENTRY_DETAILS";
