export const GET_PAYMENT_RELATED_CREDS_AND_DATAS = "GET_PAYMENT_RELATED_CREDS_AND_DATAS";
export const CARD_POLLING = "CARD_POLLING";
export const PAYMENT_VALIDATE = "PAYMENT_VALIDATE";
export const ORDER_CONFIRM = "ORDER_CONFIRM";