export const GET_RECOURCES_PRACTITIONER = "GET_RECOURCES_PRACTITIONER";
export const GET_RECOURCES_REP = "GET_RECOURCES_REP";
export const GET_RECOURCES_REP_BY_ID = "GET_RECOURCES_REP_BY_ID";
export const GET_RECOURCES_PRACTITIONER_BY_ID = "GET_RECOURCES_PRACTITIONER_BY_ID";