export const SCIENCE_CATEGORIES_LIST = "SCIENCE_CATEGORIES_LIST";
export const SCIENCE_BLOG_LIST = "SCIENCE_BLOG_LIST";
export const SCIENCE_BLOG_LIST_SEARCH_WISE = "SCIENCE_BLOG_LIST_SEARCH_WISE";
export const SCIENCE_POPULAR_POST_LIST = "SCIENCE_POPULAR_POST_LIST";
export const SCIENCE_BLOGS_DETAILS = "SCIENCE_BLOGS_DETAILS";