export const GET_STORY_SECTION_DATA = "GET_STORY_SECTION_DATA";
export const GET_TREATMENT_VIDEO_DATA = "GET_TREATMENT_VIDEO_DATA";
export const GET_IMAGE_COMPRESSION_DATA = "GET_IMAGE_COMPRESSION_DATA";
export const GET_TESTIMONIAL_DATA = "GET_GET_TESTIMONIAL_DATA_DATA";